# Step 1: Use an official node image as a parent image
FROM node:16-alpine as build

# Step 2: Set the working directory in the container
WORKDIR /app

# Step 3: Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of the application code to the working directory
COPY  ./ ./

# Step 6: Build the React application
RUN npm run build

# Step 7: Use a web server image to serve the static files
FROM nginx:1.21-alpine

# Step 8: Copy the build files to the NGINX html directory
COPY --from=build /app/build /usr/share/nginx/html

# Step 9: Expose port 80 to the outside world
EXPOSE 80

# Step 10: Start NGINX server
CMD ["nginx", "-g", "daemon off;"]
